# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: deploy # Github Action에서 보여질 이름을 지정

on:
  release:
    types: [push] # push시 자동으로 실행
  push:
    branches: [master] # master 브랜치에서 동작
  workflow_dispatch: # 수동으로 실행이 가능하다.

jobs:
  build:
    runs-on: ubuntu-latest # 해당 스크립트를 작동할 OS
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # 프로젝트 코드를 Checkout한다.

    - name: Set up JDK 8
      uses: actions/setup-java@v3 # Github Action이 실행될 OS에 Java를 설치한다
      with: # 현 프로젝트는 자바 1.8버전이므로 1.8버전으로 진행한다.
        java-version: '8'
        distribution: 'temurin'

    - name : Grant execute permission for gradlew
      run : chmod +x ./gradlew # gradlew를 실행 할 수 있도록 실행권한 (+x)를 준다.
      shell : bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test # # gradlew를 통해 프로젝트를 build한다.
      shell: bash